# Generated by Django 5.0.4 on 2024-12-06 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='field',
            field=models.CharField(choices=[('Nursing', 'nursing'), ('Physic', 'physic'), ('Sanrio', 'sanrio'), ('highschool', 'highschool')], max_length=32),
        ),
        migrations.AlterField(
            model_name='battlerecord',
            name='field',
            field=models.CharField(choices=[('Nursing', 'nursing'), ('Physic', 'physic'), ('Sanrio', 'sanrio'), ('highschool', 'highschool')], max_length=32),
        ),
    ]
