# Generated by Django 5.0.4 on 2024-12-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_answerrecord_createdtime_alter_answerrecord_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrecord',
            name='field',
            field=models.CharField(choices=[('Nursing', 'nursing'), ('Sanrio', 'sanrio'), ('biology', 'biology')], max_length=32),
        ),
        migrations.AlterField(
            model_name='battlerecord',
            name='field',
            field=models.CharField(choices=[('Nursing', 'nursing'), ('Sanrio', 'sanrio'), ('biology', 'biology')], max_length=32),
        ),
    ]
