# Generated by Django 5.0.4 on 2024-12-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaming", "0003_alter_answerrecord_field_alter_battlerecord_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_username",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
