# Generated by Django 5.0.4 on 2025-01-13 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaming", "0007_alter_definition_definition_alter_definition_example"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="hashed_id",
            field=models.CharField(
                max_length=256, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="UniqueAnswerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct", models.BooleanField()),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gaming.problem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "unique_answer_record",
            },
        ),
        migrations.CreateModel(
            name="WordLearningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("learning", "learning"),
                            ("reviewing", "reviewing"),
                            ("mastered", "mastered"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_time", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gaming.word"
                    ),
                ),
            ],
            options={
                "db_table": "word_learning_record",
            },
        ),
    ]
