# Generated by Django 5.0.4 on 2025-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0008_alter_problem_hashed_id_uniqueanswerrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='test_type',
            field=models.CharField(choices=[('gre', 'gre'), ('hs7000', 'hs7000')], default='gre', max_length=32),
        ),
        migrations.AlterField(
            model_name='definition',
            name='definition',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
